#!/usr/bin/env python3
"""Build versioned Dency update pages using only the Python standard library."""
import argparse
from datetime import date, datetime, timezone
from email.utils import format_datetime
from html import escape
import json
from pathlib import Path
import re
from string import Template
import sys

ROOT = Path(__file__).resolve().parents[1]
BASE_URL = "https://amonstudioapp.github.io/chargepath-support"
GENERATED_MARKER = "<!-- Generated by scripts/build_updates.py; do not edit directly. -->\n"
VERSION_PATTERN = re.compile(r"(?:0|[1-9][0-9]{0,5})(?:\.(?:0|[1-9][0-9]{0,5})){0,2}")


def version_key(value):
    if not isinstance(value, str) or not VERSION_PATTERN.fullmatch(value):
        raise ValueError("Version must use one to three canonical numeric components")
    parts = tuple(int(part) for part in value.split("."))
    return parts + (0,) * (3 - len(parts))


def plain_text(value, label, limit=10000):
    if not isinstance(value, str) or not value.strip() or len(value) > limit:
        raise ValueError(f"{label} must be nonempty text of at most {limit} characters")
    if any(ord(char) < 32 and char not in "\n\r\t" for char in value):
        raise ValueError(f"{label} contains unsupported control characters")
    return value


def validate_blocks(blocks, label, field, required=False):
    if not isinstance(blocks, list) or len(blocks) > 100 or (required and not blocks):
        raise ValueError(f"{label} must be a {'nonempty ' if required else ''}list")
    for block in blocks:
        if not isinstance(block, dict) or set(block) != {"title", field}:
            raise ValueError(f"Invalid {label} block")
        plain_text(block["title"], f"{label} title", 200)
        if field == "description":
            plain_text(block[field], f"{label} description")
        else:
            items = block[field]
            if not isinstance(items, list) or not items or len(items) > 100:
                raise ValueError("Section items must be a nonempty list")
            for item in items:
                plain_text(item, "section item")


def validate_data(data, allow_empty=False):
    if not isinstance(data, dict) or set(data) != {"releases"}:
        raise ValueError("Content must contain only a releases list")
    releases = data["releases"]
    if not isinstance(releases, list) or (not releases and not allow_empty):
        raise ValueError("At least one release is required")
    required = {"version", "date", "title", "summary", "source", "sections"}
    allowed = required | {"highlights", "sourceNote"}
    versions = set()
    for item in releases:
        if not isinstance(item, dict) or not required <= set(item) <= allowed:
            raise ValueError("Release has missing or unsupported fields")
        normalized_version = version_key(item["version"])
        if normalized_version in versions:
            raise ValueError("Duplicate release version")
        versions.add(normalized_version)
        stamp = item["date"]
        if not isinstance(stamp, str) or not re.fullmatch(r"[0-9]{4}-[0-9]{2}-[0-9]{2}", stamp):
            raise ValueError("Release date must be YYYY-MM-DD")
        date.fromisoformat(stamp)
        plain_text(item["title"], "title", 200)
        plain_text(item["summary"], "summary")
        if item["source"] not in ("app-store", "editorial"):
            raise ValueError("Unsupported source")
        validate_blocks(item.get("highlights", []), "highlights", "description")
        validate_blocks(item["sections"], "sections", "items", required=True)
        if "sourceNote" in item:
            plain_text(item["sourceNote"], "sourceNote")
    return sorted(releases, key=lambda item: version_key(item["version"]), reverse=True)


def display_date(value):
    stamp = date.fromisoformat(value)
    return f"{stamp.year} 年 {stamp.month} 月 {stamp.day} 日"


def render_highlights(release):
    return "\n".join(
        f'<div class="highlight"><span class="highlight-number">{number:02}</span>'
        f'<h3>{escape(item["title"])}</h3><p>{escape(item["description"])}</p></div>'
        for number, item in enumerate(release.get("highlights", []), 1))


def render_sections(release):
    return "\n".join(
        f'<section class="release-section" id="section-{number}"><h2>{escape(section["title"])}</h2>'
        '<ul>' + ''.join(f'<li>{escape(item)}</li>' for item in section["items"]) + '</ul></section>'
        for number, section in enumerate(release["sections"], 1))


def render_row(release):
    version = escape(release["version"])
    return (f'<article class="release-row"><div class="release-stamp"><span class="version">v{version}</span>'
            f'<time datetime="{escape(release["date"])}">{display_date(release["date"])}</time></div>'
            f'<div><h2><a href="./{version}/">{escape(release["title"])}</a></h2>'
            f'<p>{escape(release["summary"])}</p></div><a class="read-release" href="./{version}/" '
            f'aria-label="閱讀 {version} 完整更新">閱讀更新 ↗</a></article>')


def neighbor_link(release, label):
    if release is None:
        return ""
    version = escape(release["version"])
    return f'<a href="../{version}/">{label} · v{version}</a>'


def render_feed(releases):
    items = []
    for release in releases:
        url = f'{BASE_URL}/updates/{release["version"]}/'
        published = format_datetime(datetime.combine(date.fromisoformat(release["date"]),
                                                     datetime.min.time(), timezone.utc))
        items.append(f'<item><title>{escape(release["title"])}</title><link>{url}</link>'
                     f'<guid isPermaLink="true">{url}</guid><pubDate>{published}</pubDate>'
                     f'<description>{escape(release["summary"])}</description></item>')
    return ('<?xml version="1.0" encoding="UTF-8"?>\n<rss version="2.0"><channel>'
            '<title>電程 Dency 更新日誌</title>'
            f'<link>{BASE_URL}/updates/</link><description>電程 App 最新功能與版本更新</description>'
            '<language>zh-TW</language>' + ''.join(items) + '</channel></rss>\n')


def render_site(root, releases):
    index_template = Template((root / "templates/updates-index.html").read_text(encoding="utf-8"))
    detail_template = Template((root / "templates/update-detail.html").read_text(encoding="utf-8"))
    latest = releases[0]
    pages = {"updates/index.html": index_template.substitute(
        latest_version=escape(latest["version"]), latest_date=display_date(latest["date"]),
        latest_title=escape(latest["title"]), latest_summary=escape(latest["summary"]),
        latest_url=f'./{latest["version"]}/', latest_highlights=render_highlights(latest),
        release_list="\n".join(render_row(release) for release in releases)),
        "updates/feed.xml": render_feed(releases)}
    for number, release in enumerate(releases):
        version = release["version"]
        note = f'<p class="source-note">{escape(release["sourceNote"])}</p>' if release.get("sourceNote") else ""
        pages[f"updates/{version}/index.html"] = GENERATED_MARKER + detail_template.substitute(
            version=escape(version), date=display_date(release["date"]), title=escape(release["title"]),
            summary=escape(release["summary"]), highlights=render_highlights(release),
            sections=render_sections(release), source_note=note,
            previous_link=neighbor_link(releases[number + 1] if number + 1 < len(releases) else None, "上一個版本"),
            next_link=neighbor_link(releases[number - 1] if number else None, "下一個版本"),
            canonical=f"{BASE_URL}/updates/{version}/")
    return pages


def stale_generated_pages(root, pages):
    """Identify only our marked pages; never claim arbitrary files or symlinks."""
    stale = []
    for path in (root / "updates").glob("*/index.html"):
        if (path.is_symlink() or path.parent.is_symlink() or not path.is_file()
                or not VERSION_PATTERN.fullmatch(path.parent.name)
                or str(path.relative_to(root)) in pages):
            continue
        with path.open(encoding="utf-8", errors="replace") as handle:
            if handle.read(len(GENERATED_MARKER)) == GENERATED_MARKER:
                stale.append(path)
    return stale


def build_site(root=ROOT, check=False):
    root = Path(root)
    data = json.loads((root / "data/releases.json").read_text(encoding="utf-8"))
    pages = render_site(root, validate_data(data))
    stale = stale_generated_pages(root, pages)
    fresh = not stale if check else True
    for relative, content in pages.items():
        destination = root / relative
        matches = destination.exists() and destination.read_text(encoding="utf-8") == content
        if check:
            fresh = fresh and matches
        elif not matches:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(content, encoding="utf-8")
    if not check:
        for path in stale:
            path.unlink()
            if not any(path.parent.iterdir()):
                path.parent.rmdir()
    return fresh


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check generated files without writing")
    args = parser.parse_args(argv)
    try:
        if not build_site(ROOT, check=args.check):
            print("Update pages need rebuilding: python3 scripts/build_updates.py", file=sys.stderr)
            return 1
    except (OSError, ValueError, KeyError) as error:
        print(f"Cannot build updates: {error}", file=sys.stderr)
        return 1
    print("Update pages are current." if args.check else "Update pages built.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
